# Generated by Django 4.1.4 on 2023-12-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_case_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='relationship_with_user',
            field=models.CharField(choices=[('principal_member', 'Principal Member'), ('spouse', 'Spouse'), ('dependant', 'Dependant')], max_length=50),
        ),
    ]
