# Generated by Django 4.1.4 on 2023-12-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_remove_case_deceased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='deceased_member_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='user_registration.user'),
        ),
    ]
