# Generated by Django 4.1.4 on 2023-12-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0005_case_deceased_member_name_alter_case_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='user_registration.case'),
        ),
    ]
